(function(){
  "use strict";
  if(typeof window==="undefined"||!window.document||!window.OrlojDay)return;
  var D=window.OrlojDay,A=window.Astronomy,PROFILE_KEY="orloj-public-profile-v1",OBSERVER_KEY="orloj-public-observer-v1";
  var TYPES=[{id:"phase",label:"Lunární fáze"},{id:"eclipse",label:"Zatmění"},{id:"season",label:"Sezony"},{id:"ingress",label:"Ingresy"},{id:"station",label:"Stanice"},{id:"aspect-window",label:"Aspekty"},{id:"personal",label:"Osobní"}];
  var state={start:null,end:null,range:"quarter",mode:"simple",timezone:"Europe/Prague",profile:null,data:null,types:new Set(TYPES.map(function(x){return x.id;})),planet:null,universalLimit:60,personalLimit:40,token:0};
  function $(id){return document.getElementById(id);}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function readLocal(key){try{return JSON.parse(localStorage.getItem(key)||"null");}catch(e){return null;}}
  function loadContext(){var observer=readLocal(OBSERVER_KEY),profile=readLocal(PROFILE_KEY),local=Intl.DateTimeFormat().resolvedOptions().timeZone||"Europe/Prague";state.timezone=observer&&D.validTimeZone(observer.timezone)?observer.timezone:(D.validTimeZone(local)?local:"Europe/Prague");state.profile=D.validProfile(profile)?profile:null;}
  function endFor(start){return state.range==="week"?D.shiftDateKey(start,7):D.addMonthsDateKey(start,state.range==="month"?1:3);}
  function rangeLabel(){var a=fmtDate(state.start,{day:"numeric",month:"long",year:"numeric"}),last=D.shiftDateKey(state.end,-1),b=fmtDate(last,{day:"numeric",month:"long",year:"numeric"});return a+" — "+b;}
  function fmtDate(key,options){return new Intl.DateTimeFormat("cs-CZ",Object.assign({timeZone:"UTC",day:"numeric",month:"long"},options||{})).format(D.civilDate(key));}
  function dateKey(at){return D.dateKeyAt(new Date(at),state.timezone);}
  function fmtMoment(at,withTime){var opts={timeZone:state.timezone,day:"numeric",month:"short"};if(withTime!==false){opts.hour="2-digit";opts.minute="2-digit";opts.hourCycle="h23";}return new Intl.DateTimeFormat("cs-CZ",opts).format(new Date(at));}
  function bodyMeta(id){return D.BODY_META.find(function(x){return x.id===id;});}
  function eventBodies(e){return[e.body,e.a,e.b,e.transit&&e.transit.id,e.natal&&e.natal.id].filter(Boolean);}
  function isSimple(e){if(e.kind!=="aspect-window"&&e.kind!=="personal")return true;if(e.kind==="aspect-window")return e.exact&&e.a!=="moon"&&e.b!=="moon"&&(e.a==="sun"||e.b==="sun"||["jupiter","saturn","uranus","neptune","pluto"].indexOf(e.a)>=0||["jupiter","saturn","uranus","neptune","pluto"].indexOf(e.b)>=0);return e.exact&&e.body!=="moon"&&e.body!=="mercury"&&e.body!=="venus";}
  function passes(e){if(!state.types.has(e.kind))return false;if(state.planet&&eventBodies(e).indexOf(state.planet)<0)return false;if(state.mode==="simple"&&!isSimple(e))return false;return true;}
  function colorClass(e){if(e.kind==="aspect-window"||e.kind==="personal")return e.kind+" "+(e.aspect?e.aspect.type:"");return e.kind;}
  function intervalText(e){if(e.start==null)return fmtMoment(e.at,true);var peak=e.peakAt==null?e.at:e.peakAt,peakText=peak<state.data.bounds.start?"vrchol před obdobím":peak>=state.data.bounds.end?"vrchol po období":fmtMoment(peak,true);return fmtMoment(e.start,false)+" → "+peakText+" → "+fmtMoment(e.end,false);}
  function detailLink(e){return"day.html?date="+encodeURIComponent(dateKey(e.at));}
  function renderEvent(e){var interval=e.start!=null,body=bodyMeta(e.body||e.a),accent=body?body.color:"",exact=e.exact===false?'<span class="river-near">největší přiblížení</span>':"";return '<a class="river-event '+colorClass(e)+'" href="'+detailLink(e)+'"'+(accent?' style="--body:'+accent+'"':"")+'><time>'+esc(intervalText(e))+'</time><i>'+esc(e.glyph||"•")+'</i><div><b>'+esc(e.title)+'</b><p>'+esc(e.detail||"")+'</p>'+exact+'</div><em>Profil dne →</em></a>';}
  function renderStream(id,events,limit,moreId){var box=$(id),visible=events.filter(passes),slice=visible.slice(0,limit),lastMonth="",html="";slice.forEach(function(e){var month=fmtDate(dateKey(e.at),{month:"long",year:"numeric"});if(month!==lastMonth){html+='<h3>'+esc(month.charAt(0).toUpperCase()+month.slice(1))+'</h3>';lastMonth=month;}html+=renderEvent(e);});box.innerHTML=html||'<div class="river-empty">Pro zvolený filtr zde nejsou žádné události.</div>';var more=$(moreId);more.hidden=visible.length<=limit;more.textContent="Zobrazit další · "+(visible.length-limit)+" zbývá";return visible;}
  function mapLane(e){if(e.kind==="eclipse")return 0;if(e.kind==="phase")return 1;if(e.kind==="season"||e.kind==="ingress")return 2;if(e.kind==="station")return 3;if(e.kind==="aspect-window")return 4;return 5;}
  function renderMap(universal,personal){var events=universal.concat(personal),bounds=state.data.bounds,span=bounds.end-bounds.start,labels=["Zatmění","Luna","Ingresy","Stanice","Aspekty","Osobní"],html='<div class="river-axis">';for(var i=0;i<=6;i++){var at=bounds.start+span*i/6,left=i/6*100;html+='<span style="left:'+left.toFixed(2)+'%">'+esc(fmtMoment(at,false))+'</span>';}html+='</div>';labels.forEach(function(label,index){html+='<div class="river-lane" style="top:'+(38+index*42)+'px"><label>'+label+'</label></div>';});html+='<div class="river-event-layer">';var visual=events.filter(function(e){return e.kind!=="aspect-window"&&e.kind!=="personal"||e.exact;}).slice(0,state.mode==="simple"?120:280);visual.forEach(function(e){var lane=mapLane(e),top=45+lane*42,left=Math.max(0,Math.min(100,(e.at-bounds.start)/span*100));if(e.start!=null){var x=Math.max(0,(e.start-bounds.start)/span*100),w=Math.max(.35,(Math.min(e.end,bounds.end)-Math.max(e.start,bounds.start))/span*100),offset=Math.max(0,Math.min(100,(left-x)/w*100));html+='<a href="'+detailLink(e)+'" class="river-mark bar '+colorClass(e)+'" title="'+esc(e.title)+'" style="--x:'+x.toFixed(3)+'%;--w:'+w.toFixed(3)+'%;--peak-offset:'+offset.toFixed(3)+'%;top:'+top+'px"><i></i></a>';}else html+='<a href="'+detailLink(e)+'" class="river-mark dot '+colorClass(e)+'" title="'+esc(e.title)+'" style="--x:'+left.toFixed(3)+'%;top:'+top+'px"><i>'+esc(e.glyph||"•")+'</i></a>';});$("river-map").innerHTML=html+'</div>';}
  function renderFilters(){var typeBox=$("river-type-filters"),planetBox=$("river-planet-filters");typeBox.innerHTML=TYPES.map(function(t){return '<button class="'+(state.types.has(t.id)?"on":"")+'" data-type="'+t.id+'" type="button">'+t.label+'</button>';}).join("");planetBox.innerHTML='<button class="'+(!state.planet?"on":"")+'" data-planet="" type="button">Všechny</button>'+D.BODY_META.map(function(p){return '<button class="'+(state.planet===p.id?"on":"")+'" data-planet="'+p.id+'" type="button"><i style="color:'+p.color+'">'+p.glyph+'</i>'+p.name+'</button>';}).join("");}
  function render(){if(!state.data)return;renderFilters();var universal=renderStream("river-universal",state.data.events,state.universalLimit,"river-universal-more"),personal=renderStream("river-personal",state.data.personal,state.personalLimit,"river-personal-more");renderMap(universal,personal);$("river-visible-count").textContent=(universal.length+personal.length)+" zobrazených vrstev";Array.prototype.forEach.call(document.querySelectorAll("[data-mode]"),function(b){b.classList.toggle("on",b.dataset.mode===state.mode);});}
  function updateSummary(){var thresholds=state.data.events.filter(function(e){return e.kind!=="aspect-window";}).length,aspects=state.data.events.length-thresholds;$("river-threshold-count").textContent=thresholds;$("river-aspect-count").textContent=aspects;$("river-personal-count").textContent=state.profile?state.data.personal.length:"—";$("river-personal-summary").textContent=state.profile?"vypočteno pouze z místního profilu":"profil v tomto zařízení není vytvořen";$("river-profile-name").textContent=state.profile?(state.profile.name||"Můj profil"):"bez osobního profilu";}
  function updateUrl(){try{var u=new URL(location.href);u.searchParams.set("start",state.start);u.searchParams.set("range",state.range);u.searchParams.set("mode",state.mode);history.replaceState(null,"",u);}catch(e){}}
  function compute(){var token=++state.token;state.end=endFor(state.start);$("river-content").hidden=true;$("river-status").hidden=false;$("river-start").value=state.start;$("river-period").textContent=rangeLabel();$("river-timezone").textContent=state.timezone;Array.prototype.forEach.call(document.querySelectorAll("[data-range]"),function(b){b.classList.toggle("on",b.dataset.range===state.range);});updateUrl();setTimeout(function(){try{var result=D.rangeEvents(A,state.start,state.end,state.timezone,state.profile,{stepHours:6});if(token!==state.token)return;state.data=result;state.universalLimit=60;state.personalLimit=40;updateSummary();render();$("river-status").hidden=true;$("river-content").hidden=false;}catch(error){if(token!==state.token)return;$("river-status").innerHTML='<div class="river-error"><b>Výpočet se nepodařilo dokončit.</b><span>'+esc(error&&error.message||error)+'</span></div>';console.error(error);}},30);}
  function move(direction){if(state.range==="week")state.start=D.shiftDateKey(state.start,direction*7);else state.start=D.addMonthsDateKey(state.start,direction*(state.range==="month"?1:3));compute();}
  function bind(){$("river-prev").addEventListener("click",function(){move(-1);});$("river-next").addEventListener("click",function(){move(1);});$("river-today").addEventListener("click",function(){state.start=D.dateKeyAt(new Date(),state.timezone);compute();});$("river-start").addEventListener("change",function(){if(D.parseDateKey(this.value)){state.start=this.value;compute();}});$("river-reset").addEventListener("click",function(){state.types=new Set(TYPES.map(function(x){return x.id;}));state.planet=null;render();});$("river-universal-more").addEventListener("click",function(){state.universalLimit+=80;render();});$("river-personal-more").addEventListener("click",function(){state.personalLimit+=60;render();});$("river-share").addEventListener("click",function(){var b=this,u=new URL(location.href),done=function(){b.textContent="Odkaz zkopírován ✓";setTimeout(function(){b.textContent="Sdílet výhled";},1800);};u.searchParams.set("start",state.start);u.searchParams.set("range",state.range);u.searchParams.set("mode",state.mode);if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(u.toString()).then(done).catch(function(){prompt("Zkopíruj odkaz:",u.toString());});else prompt("Zkopíruj odkaz:",u.toString());});document.addEventListener("click",function(e){var b=e.target.closest("[data-range],[data-mode],[data-type],[data-planet]");if(!b)return;if(b.dataset.range){state.range=b.dataset.range;compute();return;}if(b.dataset.mode){state.mode=b.dataset.mode;updateUrl();render();return;}if(b.hasAttribute("data-type")){var id=b.dataset.type;if(state.types.has(id))state.types.delete(id);else state.types.add(id);render();return;}if(b.hasAttribute("data-planet")){state.planet=b.dataset.planet||null;render();}});}
  function init(){loadContext();var params;try{params=new URL(location.href).searchParams;}catch(e){params=new URLSearchParams();}var requested=params.get("start"),range=params.get("range"),mode=params.get("mode");state.start=D.parseDateKey(requested)?requested:D.dateKeyAt(new Date(),state.timezone);if(["week","month","quarter"].indexOf(range)>=0)state.range=range;if(mode==="study")state.mode="study";bind();if(!A){$("river-status").innerHTML='<div class="river-error">Astronomický výpočtový modul se nepodařilo načíst.</div>';return;}compute();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
